### PR TITLE
added the LLM

### PR DESCRIPTION
**Pull request by ArshErgon**
for the issue: #7  I have added the LLM, run tests also

### CODE REVIEW

**Comment by mmirman** [comment]
@cartazio @VictorOdede Is this still relevant?

**Comment by VictorOdede** [comment]
> @cartazio @VictorOdede Is this still relevant?

I had split this into 2 separate tasks to make it more manageable. One for Nvidia quantization and the other for quantization on all other hardware. See #224 and #225

**Comment by mmirman** [comment]
What about this PR?

**Comment by VictorOdede** [comment]
> What about this PR?

This PR potentially closes #224. Just 2 suggestions to make it more complete:

- Add config and params for 8bit quantization
- Add support for all other models not just `facebook/opt`

**Pull request closed without merging**
