### PR TITLE
Added class for OpenAI's gpt-4 model

### PR DESCRIPTION
**Pull request by MehmetMHY**
Added model class for OpenAI's GPT-4 model. Also cleaned up `src/llm_vm/onsite_llm.py` using vscode's Prettier extension.

### CODE REVIEW

**Review by T3CH3Y — APPROVED** [review]
Appreciate the prettify. GPT class looks good. Finetune exception is weird imo but seems be a going theme here lol.

**Review by VictorOdede — COMMENTED** [review]
looks good but seems to me like a lot of formatting changes have been added to this. Please modify this to only include your code changes and revert formatting changes

**Comment by MehmetMHY** [comment]
Noted, will do

**Comment by MehmetMHY** [comment]
Ok, I closed this PR and created a new PR with the same changes but with no Prettify. Check it out here: https://github.com/anarchy-ai/LLM-VM/pull/321

**Pull request closed without merging**
