### PR TITLE
Feature/andrew/prelim open llm wrappers

### PR DESCRIPTION
**Pull request by ajn2004**
Adds preliminary functionality for onsite LLMs through onsite_llm.py file. Refactors app.py into directory allowing us to modularize functionality moving forward, keeping our code organized and easily navigable. Running "python app.py" from the top folder should result in a hosting of the app w/ all current functionality of main

### CODE REVIEW

**Review by mmirman — COMMENTED** [review]
Looks good, it'd be better if @cartazio gave it a review!

**Comment by cartazio** [comment]
I can fix these up though, if we wanna just merge em in

**Comment by ajn2004** [comment]
Apologies on the pyproject file, I thought I started from your branch and moved forward, but it must have been overwritten by the merge with main. 

I'll follow up with you on the other issues to prevent these from reoccurring.

**Comment by cartazio** [comment]
Oh, I can rebase my changes ontop of main if that would help.

**Pull request merged**
