### PR TITLE
[Doc fix]- Added Installation instructions for Windows OS

### LINKED ISSUE #323: Install script for Windows
We currently only have an install script for MacOS

### LINKED ISSUE #345: Installation Steps in README.md failing for Windows
The installation steps given in the README.md are working only for MacOS. 
```
git clone https://github.com/anarchy-ai/LLM-VM.git
cd LLM-VM
./setup.sh
```
After running the above lines, it is showing: 
```
$ ./setup.sh

* You can skip steps by passing [-s "os brew python direnv poetry deps"]

* Checking OS..
This script only works on MacOS. Found unsupported OS: MINGW64_NT-10.0-22621
```

Can we please change it?
Thank you!

### PR DESCRIPTION
**Pull request by daredevilteja**
Closes #323 and #345

### CODE REVIEW

**Comment by daredevilteja** [comment]
Please check it @VictorOdede @abhigya-sodani

**Review by VictorOdede — COMMENTED** [review]
Thanks for the contribution. This is a good addition but it doesn't close out #323. That requires you add a bash script for windows installation.

**Review by VictorOdede — CHANGES_REQUESTED** [review]
Kindly change to Python version 3.11

**Comment by VictorOdede** [comment]
Also this only closes #345

**Comment by daredevilteja** [comment]
@VictorOdede

**Comment by VictorOdede** [comment]
windows_setup_error
Hey @daredevilteja I'm getting this error while trying to run the script

**Comment by daredevilteja** [comment]
Hi @VictorOdede I have fixed the error and updated the readme. Please run the tests now.

**Review by VictorOdede — APPROVED** [review]
LGTM!

**Pull request merged**
