### PR TITLE
Implement Code Llama in LLM-VM

### PR DESCRIPTION
**Pull request by bilal-aamer**
Closes https://github.com/anarchy-ai/LLM-VM/issues/190

### CODE REVIEW

**Comment by bilal-aamer** [comment]
@VictorOdede Kindly review

**Review by VictorOdede — CHANGES_REQUESTED** [review]
Looks good! Kindly change the class naming to be more intuitive like `SmallLocalCodeLlama` should just be `CodeLlama7b`

**Comment by bilal-aamer** [comment]
All done, kindly review @VictorOdede

**Review by VictorOdede — CHANGES_REQUESTED** [review]
LGTM! Thanks for your contibution

**Review by VictorOdede — APPROVED** [review]
LGTM

**Pull request merged**
