### PR TITLE
feat: auto device selection, cpu, gpu, multi-gpu

### LINKED ISSUE #172: Work with all hardware automatically

### LINKED ISSUE #173: Automatically go to the CPU if GPU isn't available.

### PR DESCRIPTION
**Pull request by us**
close #173

- [ ] Needs tests on GPU and multi-gpu

### CODE REVIEW

**Comment by mmirman** [comment]
@abhigya-sodani do you have devices we can test this on?

**Comment by cartazio** [comment]
@us  this looks good to merge afaict, @VictorOdede  any thoughts?

**Comment by VictorOdede** [comment]
@carter this pr looks good to me. Should be ready to merge.

**Comment by VictorOdede** [comment]
@us I changed the original comment to close out #173 only since this doesn't really enable the models to run all hardware

**Comment by us** [comment]
@VictorOdede Hey, can you give me details a bit for fixing it? another option that comes to my mind is using hugging face `device_map=auto` but I saw some problems in this function cuz of I used manual cuda device selection. Maybe I can try that too, what do you think about it?

**Comment by VictorOdede** [comment]
Hey @us the problem is that the hf models are cuda accelerated so apart from cpu, it won't run on other hardware such as amd, intel gpu, m1 etc. My suggestion would be to look into the hardware specific libs e.g ROCm, metal and find a way to wrap or transpile the cuda functions. You can open a new PR to tackle this issue on a per-device basis.

Were you able to make fixes to the qlora PR?

**Comment by us** [comment]
@VictorOdede I didn't make any changes for GPU for avoiding confusion with this pr in qlora pr, so let me add `device_map=auto` to there, like the suggested way! 

Mentioned suggestion ref:
[As a general rule, we recommend users to not manually set a device once the model has been loaded with device_map. So any device assignment call to the model, or to any model’s submodules should be avoided after that line - unless you know what you are doing.](https://huggingface.co/blog/4bit-transformers-bitsandbytes#:~:text=As%20a%20general%20rule%2C%20we%20recommend%20users%20to%20not%20manually%20set%20a%20device%20once%20the%20model%20has%20been%20loaded%20with%20device_map.%20So%20any%20device%20assignment%20call%20to%20the%20model%2C%20or%20to%20any%20model%E2%80%99s%20submodules%20should%20be%20avoided%20after%20that%20line%20%2D%20unless%20you%20know%20what%20you%20are%20doing.)

**Comment by VictorOdede** [comment]
Thanks for the reference @us. I think the key point is "unless you know what you're doing". Luckily, we know exactly what we're doing😄 Since we're already getting/setting the device in the global state we can still use it to configure the finetuning. This will help us to distribute the finetuning if necessary

**Pull request merged**
