### PR TITLE
Refactor completions

### PR DESCRIPTION
**Pull request by fedegr**
Refactor completions to have all completions in the same class (configuring just the generator)
Refactor data_synthesis to remove multiple ifs with the same logic pattern

### CODE REVIEW

**Comment by fedegr** [comment]
I did not have the chance to test the code given I do not have access to OpenAI and there is no automated test suite.

**Comment by fedegr** [comment]
This is why I think this improves readability and code quality on data_synthesis.py:
- The original logic has regex, type, and choices parameters in the input, but they can not be used all at the same time, so it is confusing for a user of the generate_example method to know how it will work without knowing the implementation (I may expect that all options can have an impact at the same time)
- The 3 options have nearly the same code (just changing the Completion)
- The else case (no completion selected) is again almost the same code just using the prompt as the result of the completion (again just changing the completion)
- It is not easy to understand the return of the function when an error happens (the tuple is never defined if there is an error in the json.loads)
- Receiving only one completion removes the switch knowledge of which completions you have at data synthesis, so adding new completions would not require changes at that file (partially true in the refactor, given I just changed the generate_example method signature to keep the public interface the same)

Having only one parameter with only one completion (the one selected by the user) removes all the previous issues.

On guided_completion.py:
- Again we have 3 classes with almost the same logic, so you need to check multiple places to find differences.

Having only one class that creates different instances based on different values removes that complexity. I would add more classes just when needed.

Moving the `if`s from data_synthesis to guided_completion means the logic to select the correct completion is in only one place, which is the place where all the completions are defined.

Can you tell me which breaking changes are in this commit?

Also, the free personal account offers 18 USD (which is a lot) but only for 3 months, and I played a bit with OpenAI at the beginning of the year, so I do not have valid credit.

**Comment by fedegr** [comment]
I found a place where the refractor is still missing (sorry about that) I'll take a look at it tomorrow, but I still think all the other points are still valid (what's more, one of those places is another place where we do the same ifs to select the completion, which doing it in a different offer could generate a bug really difficult to find)

**Comment by abhigya-sodani** [comment]
Sounds good, this is in the optimize.py file right?

Also I think your work corresponds with https://github.com/anarchy-ai/LLM-VM/pull/154, and I will be merging this PR in soon, so you might have some changes needed after that happens.

**Comment by fedegr** [comment]
> Sounds good, this is in the optimize.py file right?
> 
> Also I think your work corresponds with #154, and I will be merging this PR in soon, so you might have some changes needed after that happens.

Yes, it was missing on optimize. It is already fixed.

Now we can keep everything as it is now, or check if we want to keep the 3 completions as separate parameters on the optimizer (or more after the PR is merged), or change the optimizer to receive a "guided completion" object and let the final user create the guided completions.

**Comment by abhigya-sodani** [comment]
The PR as been merged with another method and guided completetion, if you want to incorporate that into your refactor now it should be possible

**Comment by fedegr** [comment]
@abhigya-sodani the conflicts are fixed. If you can take a look at the PR and run some cases to check everything is ok, it would be nice.

**Comment by mmirman** [comment]
@fedegr Hey sorry for the slow review time on this.  I'll merge it if you can just double-check that it is still good.

**Comment by VictorOdede** [comment]
@mmirman seems to me that this PR is stale. We should consider closing it for now. If @fedegr is still interested in working on this they can open a new PR.

**Comment by cartazio** [comment]
This looks like while this has good changes, it needs to be rebased/or cherrypicked, @VictorOdede  if you think this is a good cleanup could you cherrypick the changes since you're most familiar with that work? :)

**Comment by cartazio** [comment]
or otherwise close :)

**Comment by cartazio** [comment]
@VictorOdede or just use the webgui to resolve the conflicts

**Review by VictorOdede — APPROVED** [review]
PR looks good. Will try to fix merge conflict before merging

**Comment by fedegr** [comment]
I just fixed the conflict.

**Pull request merged**
