### PR TITLE
adding additional reference toward glossary.md file

### PR DESCRIPTION
**Pull request by lucylililiwang**

### CODE REVIEW

**Comment by lucylililiwang** [comment]
working on Queuing_for_concurrent_requests_REST

**Comment by lucylililiwang** [comment]
@lucylililiwang
[working on Queuing_for_concurrent_requests_REST](https://github.com/anarchy-ai/LLM-VM/pull/372/commits/a324a8f53b770bf88fed29ed5c18e0ec743f1a1f)

**Review by VictorOdede — CHANGES_REQUESTED** [review]
I can merge the glossary changes but you will need to open a separate PR for the concurrent request handling. This PR should only have the glossary changes.

**Comment by lucylililiwang** [comment]
Thank you! Vik! I will open another new PR

**Comment by VictorOdede** [comment]
Hey @lucylililiwang. Kindly try to keep the commit tree clean. On your fork you should create a branch for each new task you're addressing. For example, you could have one branch for `glossary_changes` and another for `gpt_finetuning`. Then open new PRs from each unique branch to avoid mixing up your commit tree.

**Pull request closed without merging**
