### PR TITLE
Depreciate flask

### PR DESCRIPTION
**Pull request by bilal-aamer**
Depreciates the `flask` dependency to a more recent stable version.
i.e. `2.3.2` -> `2.2.5`

The following notebook can be a beginner friendly notebook: [Beginner Notebook](https://colab.research.google.com/drive/1QSC-nsmQ62mtX7Pt6POBbCko_iFrtKSm?usp=sharing)

Closes https://github.com/anarchy-ai/LLM-VM/issues/152

### CODE REVIEW

**Comment by bilal-aamer** [comment]
@VictorOdede @cartazio 

Kindly review.

**Comment by cartazio** [comment]
Why did you down grade the version … this seems incorrect

**Comment by bilal-aamer** [comment]
There was an issue when importing the latest version of `flask` and `2.2.5` was the version that didn't through any issue when importing it on a Google Collab when running

`!pip install llm-vm`

After this one can essentially use the `llm_vm` module as usual.

I have attached a colab notebook for reference.

**Comment by VictorOdede** [comment]
Is there a way to do this without downgrading Flask?

**Comment by bilal-aamer** [comment]
As per the discussions, `flask` was the module that was causing the issue, kept its version towards the latest that's compatible.

**Comment by cartazio** [comment]
Why couldn’t you use virtual env ?

**Comment by cartazio** [comment]
wontfix

**Pull request closed without merging**
