### PR TITLE
Added Support For Linux along with Mac

### PR DESCRIPTION
**Pull request by mr-shitij**
I have updated the setup.sh file so that it will work for both Linux and Mac.
Issue Addressed: #324

@VictorOdede can you please look into it and let me know if any changes required ..!!

### CODE REVIEW

**Comment by mr-shitij** [comment]
@mmirman can you please look at this ...!!

**Comment by mmirman** [comment]
if this closes and issues you need to write "closes #issuenum"

**Comment by mmirman** [comment]
I am also not qualified to review this

**Review by VictorOdede — APPROVED** [review]
Thanks for the great work! This looks good to me. Will run a few tests before merging.

**Comment by VictorOdede** [comment]
@mr-shitij why is `reload_shell` commented out?

**Comment by mr-shitij** [comment]
> @mr-shitij why is `reload_shell` commented out?

Because, we already told the user to reload the shell so no need to reload in code; when the user restarts the shell it will work.

**Comment by VictorOdede** [comment]
@mr-shitij then we should remove the reload shell function instead of commenting it out

**Comment by mr-shitij** [comment]
> @mr-shitij then we should remove the reload shell function instead of commenting it out

I will do it..!!.

**Comment by mr-shitij** [comment]
@VictorOdede Can You Please Check Now ..!! I have done with changes ..!!

**Comment by mr-shitij** [comment]
closes #324

**Pull request merged**
