### PR TITLE
Feature/carter/more qol example gen reliability

### PR DESCRIPTION
**Pull request by cartazio**
make generating examples more reliable/robust

### CODE REVIEW

**Comment by cartazio** [comment]
shoot, its confused because of the squash i did for the other merge, i'll fix that up later

**Comment by cartazio** [comment]
should be ok to merge cleanly now

**Comment by cartazio** [comment]
@abhigya-sodani LTGTU?

**Comment by cartazio** [comment]
this should resolve https://github.com/anarchy-ai/LLM-VM/issues/29

**Review by abhigya-sodani — APPROVED** [review]

**Pull request merged**
