### PR TITLE
Add Glossary file 

### PR DESCRIPTION
**Pull request by Alkahwaji**
Update #258   
Adding a glossary file for basic terms in LLM for developers.

### CODE REVIEW

**Comment by VictorOdede** [comment]
Looks good to me. @mmirman do you think anything needs to be added to the glossary?

**Review by VictorOdede — APPROVED** [review]

**Comment by julietanarchy** [comment]
@Alkahwaji Hi! What is your discord handle?

**Comment by Alkahwaji** [comment]
@julietanarchy Hi, Alkahwaji#0969

**Comment by julietanarchy** [comment]
I don't see you in the discord! If you can join, https://discord.gg/anarchy-ai I will send a congratulations ping in #general for your first PR

**Comment by Alkahwaji** [comment]
@julietanarchy Joined. Thanks

**Comment by yuqianlucy** [comment]
Adding a search bar for glossary file.

**Pull request merged**
