### PR TITLE
finetune chat_gpt

### LINKED ISSUE #132: Support fine-tuning for chatgpt 3.5
We can fine-tune gpt 3.5 i.e chat_gpt according to [official blog](https://openai.com/blog/gpt-3-5-turbo-fine-tuning-and-api-updates) and [docs](https://platform.openai.com/docs/guides/fine-tuning)

So, isn't it a good idea to remove the below line and make sure fine-tuning happens?
https://github.com/anarchy-ai/LLM-VM/blob/3b4ade5a40c5160b71642373ae19ba8391066f84/src/llm_vm/onsite_llm.py#L444

Note: `gpt-3.5-turbo-0301` is used in `generate` method but `gpt-3.5-turbo-0613` supports fine-tuning. Suffix is a different number.

### PR DESCRIPTION
**Pull request by INF800**
closes #132

### CODE REVIEW

**Comment by abhigya-sodani** [comment]
```
Traceback (most recent call last):
  File "C:\Users\Abhigya Sodani\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\Abhigya Sodani\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Abhigya Sodani\AppData\Local\Programs\Python\Python311\Lib\site-packages\llm_vm\completion\optimize.py", line 42, in new_thread
    t[0] = foo()
           ^^^^^
  File "C:\Users\Abhigya Sodani\AppData\Local\Programs\Python\Python311\Lib\site-packages\llm_vm\onsite_llm.py", line 474, in start
    fine_tuning_job = openai.FineTuningJob.create(training_file=upload_response.id, model='gpt-3.5-turbo')
                      ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'FineTuningJob'
```

**Comment by abhigya-sodani** [comment]
got that error when testing

**Comment by INF800** [comment]
@abhigya-sodani It was working in my codespace after `pip install -e .`. I think your openai library does not have updates after improvements made to legacy API. 

You may need to update openai package.

**Comment by INF800** [comment]
@abhigya-sodani just checked openai's release history, will need to change version in toml file. Will make the required changes, thanks!

**Comment by abhigya-sodani** [comment]
Have you had a chance to change the TOML file

**Comment by INF800** [comment]
Hi, sorry for the late reply. I won't be able to work on it due to some
other commitments.. it's just a change in toml file to latest version.
Hopefully someone can take over.

Sorry for inconveniences.

Best,
Rakesh

**Pull request closed without merging**
