### PR TITLE
feat: added lora/qlora support

### LINKED ISSUE #97: Add LoRA, QLoRA fine-tuning for HF models
Current onsite LLM class uses full parameter fine-tuning which costly. LoRA fine-tuning will require less memory and prevent overfitting by freezing the pretrained weights.

### LINKED ISSUE #222: Implement LORA\QLORA for Nvidia GPUs
Can be done with `peft` and `bitsandbytes`

### LINKED ISSUE #223: Implement LORA\QLORA for all hardware
implement support for CPUs and other GPUs

### PR DESCRIPTION
**Pull request by us**
close #222
close #223 
close #97

### CODE REVIEW

**Comment by mmirman** [comment]
Nice work! Can you put more documentation in this pull request?

**Comment by us** [comment]
Thank you @mmirman, more documentation added!

**Comment by mmirman** [comment]
Sorry I meant here, in the discussion :-)

**Comment by mmirman** [comment]
@us I pulled in a few PRs that you took a look at.  I'm inclined to merge this today - could you maybe take a look at the errors?

**Comment by VictorOdede** [comment]
> @us I pulled in a few PRs that you took a look at. I'm inclined to merge this today - could you maybe take a look at the errors?

According to my understanding `peft` library only supports Nvidia gpus meaning this specific implementation wouldn't work on other hardware even with automated hardware detection.

**Comment by VictorOdede** [comment]
The PR looks great and seems to close out #222. I'd only request @us to add support for 8 bit QLora

**Comment by VictorOdede** [comment]
> > > @us I pulled in a few PRs that you took a look at. I'm inclined to merge this today - could you maybe take a look at the errors?
> > 
> > 
> > According to my understanding `peft` library only supports Nvidia gpus meaning this specific implementation wouldn't work on other hardware even with automated hardware detection.
> 
> According to the [releases](https://github.com/huggingface/peft/releases) page of the PEFT repository, the model also supports XPU and NPU devices. XPU is a generic term for any kind of processing unit, such as CPU, GPU, TPU, etc. NPU is a neural processing unit, which is a specialized hardware accelerator for deep learning applications.
> 
> As for AMD GPUs, I could not find any official information about their support for PEFT model. However, I found a GitHub repository called [AutoGPTQ](https://github.com/PanQiWei/AutoGPTQ), which claims to integrate with PEFT to use GPTQ quantized model to train adapters. It also provides some performance comparison charts that include AMD GPUs.

Great! The main goal it to support fine-tuning on all consumer devices so this is great news. I guess this should enable Lora on all devices. On the other hand, Qlora might not work for non-Nvidia devices since quantization config uses `bitsandbytes` which is essentially a `cuda` wrapper. This will probably be solved once we implement #225.

**Comment by VictorOdede** [comment]
Other than that I think the PR looks great and should be ready to merge. @mmirman @cartazio Kindly confirm. @us Do you mind adding a test file for this?

**Comment by cartazio** [comment]
My main concern is what Vic said, that this will only be testable on cuda devices, but thats fine i guess

**Comment by cartazio** [comment]
we should try to have some informative error message or exit/exception to handle that case I think

**Comment by cartazio** [comment]
shoot, forgot we were wanting a test, @us can you do a followup pr with that machinery? :)

**Comment by VictorOdede** [comment]
Hey @us I'm reverting this merge because it it currently breaking the `BaseOnsiteLLM` class. Kindly complete the 8 bit quantization implementation to avoid adding bugs to the codebase.

**Comment by us** [comment]
@VictorOdede hey, can you explain the error more, please?

where is it breaking?
should I add less kwargs? or shouldn't I add to kwargs? 
or should I add separate kwargs like that?
```
    def __init__(self,model_uri=None,tokenizer_kw_args={},model_kw_args={}, quantization_kw_args={}):
```
or should I add as separete function in class?
```
def model_quantizater(self):
	......
```
 Thank you!

**Comment by VictorOdede** [comment]
> @VictorOdede hey, can you explain the error more, please?
> 
> where is it breaking? should I add less kwargs? or shouldn't I add to kwargs? or should I add separate kwargs like that?
> 
> ```
>     def __init__(self,model_uri=None,tokenizer_kw_args={},model_kw_args={}, quantization_kw_args={}):
> ```
> 
> or should I add as separete function in class?
> 
> ```
> def model_quantizater(self):
> 	......
> ```
> 
> Thank you!

You need to fix the unresolved conditional branch on line 106. You should also package the logic into it's own method, the `init` method is reserved for initializing the `BaseOnsiteLLM` class.

**Pull request merged**
