### PR TITLE
Grammar constraints

### PR DESCRIPTION
**Pull request by VictorOdede**
This is a PR for #106. I have implemented generation constraints for Python and JSON grammar. The implementation can be extended to include support for other types of grammars.

### CODE REVIEW

**Comment by VictorOdede** [comment]
Hi @cartazio , @abhigya-sodani . I've integrated grammar constraints for HuggingFace models using Lark lalr parser. Kindly review the code when you have a chance

**Comment by abhigya-sodani** [comment]
Hey,
Could you post a screenshot of code you would use to test this and its output?

**Comment by VictorOdede** [comment]
> Hey, Could you post a screenshot of code you would use to test this and its output?

Hey, I've included a test file in the PR named `test_grammar_constraints.py`. Should I add a screenshot of the output?

**Comment by abhigya-sodani** [comment]
Yeah if you could

**Comment by VictorOdede** [comment]
> Yeah if you could
python_test
python_out


Here's the snippet for the Python constraints

**Comment by abhigya-sodani** [comment]
Hey, this looks amazing!

Did you also add support for grammar-based completions to the optimizer.py file

```
if regex is not None:
                    best_completion = RegexCompletion.complete(prompt,regex)
                elif type is not None:
                    best_completion = TypeCompletion.complete(prompt,type)
                elif choices is not None:
                    best_completion = ChoicesCompletion.complete(prompt,choices)
                else:
                    best_completion = self.call_big(prompt, **kwargs)
```

^lines 247-254

**Comment by VictorOdede** [comment]
> Hey, this looks amazing!
> 
> Did you also add support for grammar-based completions to the optimizer.py file
> 
> ```
> if regex is not None:
>                     best_completion = RegexCompletion.complete(prompt,regex)
>                 elif type is not None:
>                     best_completion = TypeCompletion.complete(prompt,type)
>                 elif choices is not None:
>                     best_completion = ChoicesCompletion.complete(prompt,choices)
>                 else:
>                     best_completion = self.call_big(prompt, **kwargs)
> ```
> 
> ^lines 247-254

Thanks @abhigya-sodani.  I had forgot about that but I've added it now.

**Pull request merged**
