### PR TITLE
Pull in agents from LLM-VM-add-agents branch

### PR DESCRIPTION
**Pull request by digitalnomd**
wip

### CODE REVIEW

**Comment by mmirman** [comment]
To get up-to-speed, it would be good to sync with @abhigya-sodani who's the main author on the REBEL paper in discord

**Comment by cartazio** [comment]
Hey, it looks like you got the from,to parts of a rebase wrong, so your new commits are before the rest of the code base and the diffs are confusing.

**Comment by cartazio** [comment]
oh i see whats happening, could you repoint the merge request to be against the LLM-VM-add-agents branch,

**Comment by digitalnomd** [comment]
> oh i see whats happening, could you repoint the merge request to be against the LLM-VM-add-agents branch,

Just removed my commit that resolved the merge conflicts and now everything is the same as what's on the LLM-VM-add-agents branch. This needs to be pulled into the `main` branch right? The git history might look a little strange but can be resolved with a squash.

**Comment by cartazio** [comment]
Why don’t you rebase your commits on top of the base branch or soemthing? I’m sorry that I’m adding to the confusion, I tend to use a rebase rather than merge work flow so that I can treat my changes as a diff, there’s some pretty nice graphical tools that might help like sublime merge

**Comment by cartazio** [comment]
it seems to only have commits by AB, should it have commits by you or am i just confused?

**Comment by digitalnomd** [comment]
> it seems to only have commits by AB, should it have commits by you or am i just confused?

No commits from me yet 🙂. Wanted to get the context first before contributing. Tried to specify that with "wip" in the initial comment. Sorry for the confusion.

**Pull request closed without merging**
