### PR TITLE
track disk usage

### PR DESCRIPTION
**Pull request by zhsueh**
Closes https://github.com/anarchy-ai/LLM-VM/issues/138

### CODE REVIEW

**Comment by VictorOdede** [comment]
Why is disk usage an important metric to track?

**Comment by VictorOdede** [comment]
do you have a screenshot of this running?

**Comment by zhsueh** [comment]
@VictorOdede 

 Disk Usage:
|████████████████████████████████------------------| 63.7%

**Comment by VictorOdede** [comment]
> @VictorOdede
> 
> Disk Usage: |████████████████████████████████------------------| 63.7%

how is this different from your previous PR that was closed by @cartazio ?

**Comment by zhsueh** [comment]
> > @VictorOdede
> > Disk Usage: |████████████████████████████████------------------| 63.7%
> 
> how is this different from your previous PR that was closed by @cartazio ?
For the first PR, not all disks were looped and 7 other files were submitted in the PR that are not part of the current issue and should be re-issued. The issue is that the file does not exist or the package is not imported. If the 7 file error reappears, you will see the issue.

**Comment by VictorOdede** [comment]
i thought we were only looking to keep track of the huggingface caches. Doesn't this scan the entire disk?

**Review by VictorOdede — CHANGES_REQUESTED** [review]
is it possible to track disk usage specifically for the huggingface caches?

**Pull request closed without merging**
