### PR TITLE
 Rename onsite_llm classes to follow PEP 8 standard Closes #195

### LINKED ISSUE #195: Rename onsite_llm classes to follow PEP 8 standard
Rename open_llm classes to follow [PEP8 Class Names (CammelCase)](https://peps.python.org/pep-0008/#class-names)

### PR DESCRIPTION
**Pull request by 4imothy**
Renamed many classes and fixed comments for __private_key_value_models_map.

### CODE REVIEW

**Review by us — CHANGES_REQUESTED** [review]
hahaha :D thank you for that commit and there is a small line here that you missed, 
class:
https://github.com/anarchy-ai/LLM-VM/blob/3695703b634ccf94a03a7f8b505c85c81d13c109/src/llm_vm/completion/optimize.py#L56

usage:
https://github.com/anarchy-ai/LLM-VM/blob/3695703b634ccf94a03a7f8b505c85c81d13c109/src/llm_vm/completion/optimize.py#L178
Can you also rename this and usages in this commit?

**Comment by 4imothy** [comment]
Implemented, thanks for the note

**Comment by us** [comment]
Great😊 Thank you 🙏  please squash the commits :) here is how you can do it https://github.com/anarchy-ai/LLM-VM/pull/205#issuecomment-1704370943

**Comment by 4imothy** [comment]
They have been squashed thank you for helping me 😊

**Review by us — APPROVED** [review]
you can also change the commit message to that ` chore: corrected class names to use CamelCase`

**Comment by 4imothy** [comment]
Changed the message

**Pull request merged**
