### PR TITLE
Add new LLMs

### PR DESCRIPTION
**Pull request by bilal-aamer**
Closes https://github.com/anarchy-ai/LLM-VM/issues/314

### CODE REVIEW

**Comment by bilal-aamer** [comment]
@VictorOdede Kindly review

**Comment by bilal-aamer** [comment]
@VictorOdede Any update?

**Review by VictorOdede — CHANGES_REQUESTED** [review]
Thanks for this contribution. PR looks good but you should remove the `quantized-llama` instance since it's already implemented in the code

**Comment by bilal-aamer** [comment]
@VictorOdede All done!

**Comment by VictorOdede** [comment]
> @VictorOdede All done!

Thanks! LGTM

**Pull request merged**
