### PR TITLE
Issue 164: Add setup and install script

### LINKED ISSUE #164: ERROR: Package 'llm-vm' requires a different Python: 3.9.6 not in '>=3.10'
I was trying to install Anarchy but faced some issues with the Python version. 

I tried `conda create -n myenv python=3.9.6` but it did not work.

### PR DESCRIPTION
**Pull request by bjornaer**
Closes #164 

On this PR the following changes take place:

- Add setup.sh script
    - checks user OS
    - installs homebrew for MacOS
    - sets pyenv to manage python versions/envs
    - installs python >= 3.10
    - installs direnv to handle dev local env
    - installs poetry to manage deps
    - installs dependencies
- Modify TOML pyproject to be `poetry` compliant
- create `.envrc` file to be used by `direnv` to set local dev environment
- Modify README to instruct use of new script

### CODE REVIEW

**Comment by cartazio** [comment]
We aren’t switching to poetry I thought ….

**Comment by cartazio** [comment]
Please remove poetry.

**Comment by bjornaer** [comment]
> We aren’t switching to poetry I thought ….

Oh, I did not know it was decided, my bad, will remove in a couple of hours (not home ATM)

**Comment by cartazio** [comment]
I’m also more broadly confused about install scripts.  This looks like an excellent candidate install script, I’m uncertain if we should actually be managing a users python environment

**Comment by cartazio** [comment]
butyeah, maybe make a PR to remove the poetry bits as its own thing and we'll merge it int pronto.

I'm open to using poetry, but when I looked into it, it seemed to lack the support for flexible app entry point definitions that vanilla setup-tools `pyproject.toml` supports, and that seems important

**Comment by bjornaer** [comment]
> butyeah, maybe make a PR to remove the poetry bits as its own thing and we'll merge it int pronto.
> 
> I'm open to using poetry, but when I looked into it, it seemed to lack the support for flexible app entry point definitions that vanilla setup-tools `pyproject.toml` supports, and that seems important

would you mind giving me more context? Perhaps I can look into it, poetry in my experience has been quite a good tool to use!

**Comment by bjornaer** [comment]
> I’m uncertain if we should actually be managing a users python environment

I think given this creates a venv with an appropriate python version and installs the project deps in there, we should be fine. (if someone wants to explore or do something else they can create a venv on their own anyway)

**Comment by bjornaer** [comment]
@cartazio ping to remind for review when you are available

**Comment by bjornaer** [comment]
> seemed to lack the support for flexible app entry point definitions that vanilla setup-tools supports

You can use `poetry scripts` definition to create arbitrary entry points afaik

**Review by VictorOdede — COMMENTED** [review]
hey @bjornaer will the bash script exit if user is running windows?

**Comment by bjornaer** [comment]
> hey @bjornaer will the bash script exit if user is running windows?

@VictorOdede yes. I added first a MacOS setup support, I'm happy to expand towards other OS' but would rather do that on another PR.

**Comment by VictorOdede** [comment]
> > hey @bjornaer will the bash script exit if user is running windows?
> 
> @VictorOdede yes. I added first a MacOS setup support, I'm happy to expand towards other OS' but would rather do that on another PR.

the mac setup looks great. just wondering what's stopping you from adding windows/linux support here?

**Comment by bjornaer** [comment]
> > > hey @bjornaer will the bash script exit if user is running windows?
> > 
> > @VictorOdede yes. I added first a MacOS setup support, I'm happy to expand towards other OS' but would rather do that on another PR.
> 
> the mac setup looks great. just wondering what's stopping you from adding windows/linux support here?

A lot of change all at once; it's easier to review one script rather than 3, since they will probably have different steps I was thinking on having separate files for each OS (and setup.sh as the entry point)

**Comment by VictorOdede** [comment]
Hey @bjornaer multiple scripts in the PR isn't really a problem as long as they all work. I think it would be better to merge this with Windows and Linux support so that we don't have to open new tickets for each OS

**Comment by VictorOdede** [comment]
Hey @bjornaer i'm just gonna merge this in and then create new tickets for the windows and linux scripts and you could pick those up if you want. Thanks for this useful contribution😊

**Comment by bjornaer** [comment]
> Hey @bjornaer i'm just gonna merge this in and then create new tickets for the windows and linux scripts and you could pick those up if you want. Thanks for this useful contribution😊

My bad for the delay on responding @VictorOdede , as you might guess other things in life caught my attention haha, I did start working on the other two versions of the setup script, when you create the issues I'll open PRs for them then!

**Comment by VictorOdede** [comment]
> > Hey @bjornaer i'm just gonna merge this in and then create new tickets for the windows and linux scripts and you could pick those up if you want. Thanks for this useful contribution😊
> 
> My bad for the delay on responding @VictorOdede , as you might guess other things in life caught my attention haha, I did start working on the other two versions of the setup script, when you create the issues I'll open PRs for them then!

Hey that's understandable. I've already opened the new tickets so you can continue working on it. However, we are yet to triage the new tickets so we haven't assigned bounties yet

**Pull request merged**
